In [1]:
import numpy as np 
import matplotlib.pyplot as plt
from sympy import *
from mpl_toolkits.mplot3d import Axes3D
from numpy.linalg import matrix_power

In [2]:
mass = np.array([])
print(mass)

[]


In [3]:
mass = np.array([1, 2, 3])
print(mass)

[1 2 3]


In [4]:
mass = np.array([[1.5, 2, 3], [4, 5, 6]])
print(mass)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [5]:
mass = np.zeros((3, 7))
print(mass)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
mass = np.ones((4, 5))
print(mass)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
mass = np.eye(10)
print(mass)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [8]:
mass = np.empty((3, 3))
print(mass)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.63234836e-321]
 [4.10463701e-288 2.29812144e-311 0.00000000e+000]]


In [9]:
mass = np.linspace(1, 1000, 10)
print(mass)

[   1.  112.  223.  334.  445.  556.  667.  778.  889. 1000.]


In [10]:
mass = np.arange(5)
print(mass)

[0 1 2 3 4]


In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.arange(6)

print(a)
print(b)
print('a + b:', a+b)
print('4 * b:', a*4)
print('min(b):', b.min())
print('max(b):', b.max())
print('sum(b):', b.sum())

[1 2 3 4 5 6]
[0 1 2 3 4 5]
a + b: [ 1  3  5  7  9 11]
4 * b: [ 4  8 12 16 20 24]
min(b): 0
max(b): 5
sum(b): 15


In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print('a.T: \n', a.T)

[[1 2 3 4]
 [5 6 7 8]]
a.T: 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [13]:
a = np.array([[8, 7], [3, 4]])
print(a)
print('Det a:', np.linalg.det(a))

[[8 7]
 [3 4]]
Det a: 10.999999999999996


In [14]:
print('Det a.T:', np.linalg.det(a.T))

Det a.T: 10.999999999999996


In [15]:
print(a)
print('invertible martix: \n', np.linalg.inv(a))
print('checking: \n', np.linalg.inv(np.linalg.inv(a)))

[[8 7]
 [3 4]]
invertible martix: 
 [[ 0.36363636 -0.63636364]
 [-0.27272727  0.72727273]]
checking: 
 [[8. 7.]
 [3. 4.]]


In [16]:
a = np.array([[8, 4, 6], [9, 4, 1], [2, 5, 8]])
print(a)

[[8 4 6]
 [9 4 1]
 [2 5 8]]


In [17]:
print('rank of matrix:', np.linalg.matrix_rank(a))

rank of matrix: 3


In [18]:
mass = np.arange(1, 21, 1)
print(mass)
mass = mass.reshape(4, 5)
print(mass)
mass = mass. reshape(2, 10)
print(mass)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [19]:
a = np.arange(1, 10, 1).reshape(3, 3)
print(a)
a1 = np.linalg.inv(a)
print(a1)
v=np.array([0, 1, 1])

print('a*v:', np.dot(a1, v))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
a*v: [-3.15251974e+15  6.30503948e+15 -3.15251974e+15]


In [20]:
u = np.linalg.solve(a, v)
print(u)

[-3.15251974e+15  6.30503948e+15 -3.15251974e+15]


In [21]:
a = np.eye(3, 4, 0)
b = np.eye(3, 4, 1)
c = 2*a + b
print(c)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


In [22]:
c.flatten()

array([2., 1., 0., 0., 0., 2., 1., 0., 0., 0., 2., 1.])

In [23]:
mass=mass.reshape(4,5)

In [24]:
mass

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
mass.min(axis=0)

array([1, 2, 3, 4, 5])

In [26]:
mass.max(axis=1)

array([ 5, 10, 15, 20])

In [27]:
mass.mean()

10.5

In [28]:
mass.std()

5.766281297335398

In [29]:
mass.argmin(axis=0)

array([0, 0, 0, 0, 0], dtype=int64)

In [30]:
mass.argmax(axis=1)

array([4, 4, 4, 4], dtype=int64)

In [31]:
mass.cumsum(axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15],
       [18, 21, 24, 27, 30],
       [34, 38, 42, 46, 50]], dtype=int32)

In [32]:
mass.cumprod(axis=1)

array([[      1,       2,       6,      24,     120],
       [      6,      42,     336,    3024,   30240],
       [     11,     132,    1716,   24024,  360360],
       [     16,     272,    4896,   93024, 1860480]], dtype=int32)

In [33]:
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
b = np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
a.dot(b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
b.dot(2*a)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [37]:
matrix_power(a, 3)

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])